### ISSUE TITLE
[Enhancement] Créer un batch de rappel des prêts arrivant bientôt à expiration

### ISSUE THREAD

**Issue by aiwanesk** [pplaxine/Project10#3]
Nous aimerions, en parallèle de la correction de la gestion des prolongations de prêt (cf ticket #2), ajouter un mécanisme de rappel aux usagers des prêts arrivant bientôt à expiration. Les usagers qui le souhaitent pourront activer une option (dans leur profil sur l’application web) qui leur enverra un mail de rappel 5 jours calendaires avant la fin de leur prêt. Le mail contiendra la liste de leurs prêts en cours qui arrivent à expiration dans 5 jours ou moins avec la date d’expiration associée à chaque prêt.

Cette option sera à activer par défaut pour tous les utilisateurs lors de la mise en production.

Cette demande n’est pas urgente, vous livrerez cette évolution en même temps que celle demandé dans le ticket #1.

**Comment by pplaxine** [comment]
Bonjour,

Le mécanisme de rappel aux usagers des prêts arrivant bientôt à expiration a été implementé avec succès. 

Par défaut la durée a été fixée à 5 jours comme mentionnée dans votre demande. Néanmoins, la durée à été rendue paramétrable. Il vous est donc possible de réguler celle-ci à la hausse ou à la baisse en modifiant la constante de durée au niveau du batch. 

Le développement des nouvelles fonctionnalités a été effectué sur la branche borowingReminder.

La nouvelle version de l'application est disponible sur la branch master. Celle-ci intègre les nouvelles fonctionnalités de la branche borrowingReminder (merge effectué).

En vous souhaitant une agréable journée,

Philippe plaxine
